pokersquare: main.o cards.o desk.o visual.o
	gcc	main.o	cards.o	desk.o	visual.o -o pokersquare

main.o:
	gcc	-c main.c

cards.o:
	gcc	-c cards.c

desk.o:
	gcc -c desk.c

visual.o:
	gcc -c visual.c

clean:
	rm -rf *.o	pokersquare